### ISSUE TITLE
Broken in Emacs 24.4

### ISSUE THREAD

**Issue by zilti** [Bruce-Connor/rich-minority#6]
This seems to be broken in Emacs 24.4. As soon as I've modified `rm-blacklist` from inside customize, all I get when trying to enable the mode is
```
Warning (emacs): Couldn't find minor-mode-alist inside `mode-line-modes'. If you didn't change it yourself, please file a bug report with M-x rm-bug-report
```

**Comment by Bruce-Connor** [comment]
Have you changed your mode line in any other way? Do you use smart-mode-line or powerline?

**Comment by zilti** [comment]
Oh. Yes, I'm using actually both of them.

**Comment by Bruce-Connor** [comment]
Then you don't need to activate rich minority, smart-mode-line already makes use of it. Any configurations you make should just work. 

However, if you also turn on powerline, then your results will vary, because powerline and smart mode line are not fully compatible with each other.

**Comment by zilti** [comment]
Yes, it's powerline "undoing" what smart-power-line/rich-minority has done. Using unic0rn/powerline instead of the MELPA powerline fixes that though.

**Comment by hydandata** [comment]
I am getting this error, and I do not use sml or powerline. The minor modes are removed allright, but on every re-evaluation of init.el this shows up.

**Comment by hydandata** [comment]
This is the only modeline related config I have:

(rich-minority-mode 1)
(setf rm-blacklist (rx (zero-or-more anything)))

**Comment by Malabarba** [comment]
@hydandata What's the value of `mode-line-format` for you?

**Comment by hydandata** [comment]
("%e" mode-line-front-space mode-line-mule-info mode-line-client mode-line-modified mode-line-remote mode-line-frame-identification mode-line-buffer-identification "   " mode-line-position
 (vc-mode vc-mode)
 "  " mode-line-modes mode-line-misc-info mode-line-end-spaces)

**Comment by Malabarba** [comment]
Thanks. And what's the value of mode-line-modes for you?

**Comment by hydandata** [comment]
(#("%[" 0 2
   (help-echo "Recursive edit, type C-M-c to get out"))
 "("
 (:propertize
  ("" mode-name)
  help-echo "Major mode\nmouse-1: Display major mode menu\nmouse-2: Show help for major mode\nmouse-3: Toggle minor modes" mouse-face mode-line-highlight local-map
  (keymap
   (mode-line keymap
              (down-mouse-3 keymap
                            (abbrev-mode menu-item "Abbrev (Abbrev)" abbrev-mode :help "Automatically expand abbreviations" :button
                                         (:toggle . abbrev-mode))
                            (auto-fill-mode menu-item "Auto fill (Fill)" auto-fill-mode :help "Automatically insert new lines" :button
                                            (:toggle . auto-fill-function))
                            (auto-revert-mode menu-item "Auto revert (ARev)" auto-revert-mode :help "Revert the buffer when the file on disk changes" :button
                                              (:toggle bound-and-true-p auto-revert-mode))
                            (auto-revert-tail-mode menu-item "Auto revert tail (Tail)" auto-revert-tail-mode :help "Revert the tail of the buffer when buffer grows" :enable
                                                   (buffer-file-name)
                                                   :button
                                                   (:toggle bound-and-true-p auto-revert-tail-mode))
                            (flyspell-mode menu-item "Flyspell (Fly)" flyspell-mode :help "Spell checking on the fly" :button
                                           (:toggle bound-and-true-p flyspell-mode))
                            (font-lock-mode menu-item "Font Lock" font-lock-mode :help "Syntax coloring" :button
                                            (:toggle . font-lock-mode))
                            (glasses-mode menu-item "Glasses (o^o)" glasses-mode :help "Insert virtual separators to make long identifiers easy to read" :button
                                          (:toggle bound-and-true-p glasses-mode))
                            (hide-ifdef-mode menu-item "Hide ifdef (Ifdef)" hide-ifdef-mode :help "Show/Hide code within #ifdef constructs" :button
                                             (:toggle bound-and-true-p hide-ifdef-mode))
                            (highlight-changes-mode menu-item "Highlight changes (Chg)" highlight-changes-mode :help "Show changes in the buffer in a distinctive color" :button
                                                    (:toggle bound-and-true-p highlight-changes-mode))
                            (outline-minor-mode menu-item "Outline (Outl)" outline-minor-mode :help "" :button
                                                (:toggle bound-and-true-p outline-minor-mode))
                            (overwrite-mode menu-item "Overwrite (Ovwrt)" overwrite-mode :help "Overwrite mode: typed characters replace existing text" :button
                                            (:toggle . overwrite-mode))
                            "Minor Modes")
              (mouse-2 . describe-mode)
              (down-mouse-1 menu-item "Menu Bar" ignore :filter
                            #[(_)
                              "\300 \207"
                              [mouse-menu-major-mode-map]
                              1]))))
 ("" mode-line-process)
 (:eval
  (rm--mode-list-as-string-list))
 #("%n" 0 2
   (local-map
    (keymap
     (mode-line keymap
                (mouse-2 . mode-line-widen)))
    mouse-face mode-line-highlight help-echo "mouse-2: Remove narrowing from buffer"))
 ")"
 #("%]" 0 2
   (help-echo "Recursive edit, type C-M-c to get out"))
 " ")

**Comment by Malabarba** [comment]
Hm. That seems to imply everything is working fine.
Are you sure you're not activating `rich-minority-mode` twice by accident?

**Comment by hydandata** [comment]
Pretty sure I am not. You can see yourself if you want, https://github.com/hydandata/emacs-config/blob/master/init.el

**Comment by Malabarba** [comment]
That's really strange indeed. Does the mode seem to work despite the warning?

**Comment by Malabarba** [comment]
(Unrelated. You probably don't want to do this line:

    (add-to-list 'load-path custom-lisp-dir)

It will cause your custom settings to shadow the actual `custom.el` file)

**Comment by hydandata** [comment]
It does seem to work, at least when Emacs starts. And there is no warning, it only appears after I eval-buffer init.el.

**Comment by hydandata** [comment]
![screen shot 2015-09-30 at 13 26 03](https://cloud.githubusercontent.com/assets/1764136/10191721/ee32bfbe-6776-11e5-8dc7-a358ae8d35b8.png)

**Comment by hydandata** [comment]
For now I just did:

```elisp
(unless rich-minority-mode
  (rich-minority-mode 1))
```

To get rid of the warning

**Comment by Malabarba** [comment]
Well, if you evaluate your init.el buffer then you're activating the mode a second time. ;-)

**Comment by ethanluoyc** [comment]
I am using it with Prelude and it seems that the problem still persists

**Comment by Malabarba** [comment]
Prelude uses smart-mode-line, which already activates rich minority. Just remove from your configuration the line that activates rich-minority-mode.
