### ISSUE TITLE
[Feature request/How do I do it?] Replace default minor mode lighters with custom lighters

### ISSUE THREAD

**Issue by kaushalmodi** [Bruce-Connor/rich-minority#7]
Certain minor modes have hard-coded lighters.

- `org-indent-mode` has `" Ind"`
- `outline-mode` has `" Outl"`

Those are useful and I would like to have that indication. But I would rather replace those with something short like an intuitive unicode character.

Is there a way to replace default lighters with custom ones?
As those lighter strings are hard-coded, the only options are to hide them completely or override the whole minor mode definition in my init.

**Comment by Bruce-Connor** [comment]
Rich minority can apply arbitrary text properties to the lighter strings. So you can make a string appear any way you want with the display property. 

Do you know how to do that? I can provide a snippet when I get home.

**Comment by kaushalmodi** [comment]
Thanks! Will look into that and update this issue.

**Comment by Bruce-Connor** [comment]
Here's an example:

    (add-to-list 'rm-text-properties '("Outl\\'" 'display "ø"))

I haven't tested, but it should work.

**Comment by kaushalmodi** [comment]
Thanks for posting this; I hadn't yet got chance to read up on this. It works!
