### ISSUE TITLE
Documentation out of sync; using obsolete variables

### ISSUE THREAD

**Issue by kaushalmodi** [Bruce-Connor/rich-minority#8]
The documentation header of the package has references to `rm-excluded-modes` and `rm-hidden-modes` but you have:

```el
(define-obsolete-variable-alias 'rm-excluded-modes 'rm-blacklist "0.1.1")
(define-obsolete-variable-alias 'rm-hidden-modes 'rm-excluded-modes "0.1.1")
```

The obsolete variables are also used in the code; it looks like the [`define-obsolete-variable-alias`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Variable-Aliases.html) has the arguments swapped ([*but of course that's not the case*](https://github.com/Bruce-Connor/rich-minority/commit/f9359de5fab0326325b8294aa9af81bb680fe5e0)).

**Comment by Bruce-Connor** [comment]
Fixed, thanks for reporting.
